version: '3.8'
services:

  app:
    build: .
    image: object_counter
    ports:
    - "5000:5000"
    volumes:
    - .:/object_counter
    environment:
    - TFS_HOST=tf-serving
    - TFS_PORT=${TFS_PORT}
    - TF_MODEL_NAME=${TF_MODEL_NAME}
    - MONGO_HOST=mongo
    - MONGO_PORT=${MONGO_PORT}
    - MONGO_DB=${MONGO_DB}
    - MONGO_USERNAME=${MONGO_USERNAME}
    - MONGO_PASSWORD=${MONGO_PASSWORD}
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=${POSTGRES_PORT}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - ENV=${ENV}
    - DB=${DB}
    - PYTHONUNBUFFERED=1

    depends_on:
    - mongo
    - postgres
    - tf-serving

  tf-serving:
    image: tensorflow/serving
    ports:
      - 8500:8500
      - ${TFS_PORT}:8501
    environment:
      - MODEL_NAME=${TF_MODEL_NAME} 
      - OMP_NUM_THREADS=${TF_OMP_NUM_THREADS} 
      - TENSORFLOW_INTER_OP_PARALLELISM=${TF_TENSORFLOW_INTER_OP_PARALLELISM} 
      - TENSORFLOW_INTRA_OP_PARALLELISM=${TF_TENSORFLOW_INTRA_OP_PARALLELISM}
      - MODEL_BASE_PATH=${TF_MODEL_BASE_PATH}
    volumes:
      - ${TF_LOCAL_MODEL_PATH}:${TF_MODEL_BASE_PATH}

  torch-serving:
    image: pytorch/torchserve:latest
    ports:
      - "${PT_PORT}:8080"
      - "8081:8081"
    volumes:
      - ${PT_LOCAL_MODEL_PATH}:${PT_MODEL_BASE_PATH}

    command: torchserve --start --model-store ${PT_MODEL_BASE_PATH}/${PT_MODEL_NAME} --models ${PT_MODEL_NAME}=${PT_MODEL_NAME}.mar --ts-config ${PT_CONFIG}
    
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    ports:
      - "${MONGO_PORT}:27017"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  mongo-data:
  mongo-configdb:
  postgres_data: